# Generated by Django 5.2.3 on 2025-06-14 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeper_league_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('season', models.CharField(choices=[('2024', '2024'), ('2023', '2023'), ('2022', '2022')], max_length=4)),
                ('league_type', models.CharField(choices=[('dynasty', 'Dynasty'), ('redraft', 'Redraft'), ('keeper', 'Keeper')], default='dynasty', max_length=20)),
                ('total_rosters', models.IntegerField()),
                ('roster_positions', models.JSONField()),
                ('scoring_settings', models.JSONField()),
                ('settings', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'leagues',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeper_player_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('QB', 'Quarterback'), ('RB', 'Running Back'), ('WR', 'Wide Receiver'), ('TE', 'Tight End'), ('K', 'Kicker'), ('DEF', 'Defense')], max_length=5)),
                ('team', models.CharField(blank=True, max_length=5)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('years_exp', models.IntegerField(blank=True, null=True)),
                ('height', models.CharField(blank=True, max_length=10)),
                ('weight', models.CharField(blank=True, max_length=10)),
                ('injury_status', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='SleeperUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeper_user_id', models.CharField(max_length=50, unique=True)),
                ('sleeper_username', models.CharField(max_length=100)),
                ('sleeper_display_name', models.CharField(blank=True, max_length=100)),
                ('avatar_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sleeper_users',
            },
        ),
        migrations.CreateModel(
            name='TeamRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roster_id', models.IntegerField()),
                ('starters', models.JSONField(default=list)),
                ('settings', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.league')),
                ('players', models.ManyToManyField(blank=True, to='core.player')),
                ('sleeper_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sleeperuser')),
            ],
            options={
                'db_table': 'team_rosters',
                'unique_together': {('sleeper_user', 'league')},
            },
        ),
        migrations.AddField(
            model_name='league',
            name='users',
            field=models.ManyToManyField(through='core.TeamRoster', to='core.sleeperuser'),
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeper_transaction_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transaction_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.league')),
            ],
            options={
                'db_table': 'trades',
            },
        ),
        migrations.CreateModel(
            name='PlayerValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_source', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
            ],
            options={
                'db_table': 'player_values',
                'unique_together': {('player', 'value_source', 'date')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='league',
            unique_together={('sleeper_league_id', 'season')},
        ),
    ]
